In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],
              [4,5,6]])
a3 = np.array([[[1,2,3],
               [4,5,6]],
              [[7,8,9],
               [10,11,12]]])

In [4]:
a1

array([1, 2, 3])

In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 2, 3)

In [13]:
a1.ndim

1

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

In [16]:
a1.size

3

In [14]:
a2.size

6

In [15]:
a3.size

12

In [20]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [24]:
import pandas as pd
df1 = pd.DataFrame(a1)
df1



0
0  1
1  2
2  3

In [25]:
df2 = pd.DataFrame(a2)
df2

0  1  2
0  1  2  3
1  4  5  6

In [29]:
x = np.random.randint(0,50,size=(3,5))
x

array([[19, 38,  1, 18, 17],
       [ 9,  6, 49,  3, 24],
       [ 8, 48, 22, 34,  7]])

In [32]:
x2 = np.random.random((5,3))
x2

array([[0.33509299, 0.38240191, 0.28788228],
       [0.82956437, 0.28645897, 0.41296281],
       [0.96642873, 0.28096798, 0.40504899],
       [0.5567159 , 0.70507955, 0.27050775],
       [0.50765771, 0.20052975, 0.4082439 ]])

In [36]:
x3 = np.random.rand(5,3)
x3

array([[0.77905682, 0.63054754, 0.48320309],
       [0.38373965, 0.72579906, 0.12158088],
       [0.6706592 , 0.0988991 , 0.60871898],
       [0.82767323, 0.37412143, 0.81751858],
       [0.86514154, 0.20109916, 0.01512881]])

In [39]:
ones = np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
zeros = np.zeros((5,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
array_arrange = np.arange(0,10,2)
array_arrange

array([0, 2, 4, 6, 8])

In [45]:
a4 = np.random.randint(10,size = (2,3,4,5))
a4

array([[[[3, 5, 7, 8, 0],
         [5, 3, 5, 0, 2],
         [7, 2, 0, 5, 6],
         [1, 9, 3, 7, 9]],

        [[6, 8, 0, 5, 7],
         [0, 8, 5, 6, 2],
         [8, 1, 7, 6, 8],
         [9, 5, 8, 9, 7]],

        [[1, 0, 4, 7, 8],
         [0, 6, 0, 0, 9],
         [7, 2, 4, 3, 1],
         [2, 9, 8, 8, 7]]],


       [[[1, 5, 7, 1, 9],
         [2, 5, 4, 0, 3],
         [3, 0, 5, 3, 9],
         [6, 1, 7, 0, 6]],

        [[5, 0, 9, 7, 9],
         [6, 1, 7, 5, 3],
         [4, 6, 7, 3, 4],
         [3, 8, 3, 2, 5]],

        [[0, 7, 7, 5, 0],
         [8, 2, 0, 0, 0],
         [1, 6, 8, 6, 2],
         [3, 3, 2, 1, 6]]]])

In [49]:
a4[:1,:1,:1,:2]

array([[[[3, 5]]]])

In [50]:
a4[:,:,:,:2]

array([[[[3, 5],
         [5, 3],
         [7, 2],
         [1, 9]],

        [[6, 8],
         [0, 8],
         [8, 1],
         [9, 5]],

        [[1, 0],
         [0, 6],
         [7, 2],
         [2, 9]]],


       [[[1, 5],
         [2, 5],
         [3, 0],
         [6, 1]],

        [[5, 0],
         [6, 1],
         [4, 6],
         [3, 8]],

        [[0, 7],
         [8, 2],
         [1, 6],
         [3, 3]]]])

In [51]:
np.unique([1,2,2,3,3,3,3,4,4,5])

array([1, 2, 3, 4, 5])

In [52]:
a1[0]

1

In [53]:
a1

array([1, 2, 3])

In [54]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
a1+a2

array([[2, 4, 6],
       [5, 7, 9]])

In [56]:
np.add(a1,a2)

array([[2, 4, 6],
       [5, 7, 9]])

In [57]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [58]:
a1*a3

array([[[ 1,  4,  9],
        [ 4, 10, 18]],

       [[ 7, 16, 27],
        [10, 22, 36]]])

In [59]:
a2*a3

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 7, 16, 27],
        [40, 55, 72]]])

In [60]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
np.mod(a1,2)

array([1, 0, 1], dtype=int32)

In [64]:
a2/a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [65]:
a2//a1

array([[1, 1, 1],
       [4, 2, 2]], dtype=int32)

In [66]:
a1

array([1, 2, 3])

In [67]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
a1*a3

array([[[ 1,  4,  9],
        [ 4, 10, 18]],

       [[ 7, 16, 27],
        [10, 22, 36]]])

In [69]:
a2


array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
a2*a3

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 7, 16, 27],
        [40, 55, 72]]])

In [71]:
a4


array([[[[3, 5, 7, 8, 0],
         [5, 3, 5, 0, 2],
         [7, 2, 0, 5, 6],
         [1, 9, 3, 7, 9]],

        [[6, 8, 0, 5, 7],
         [0, 8, 5, 6, 2],
         [8, 1, 7, 6, 8],
         [9, 5, 8, 9, 7]],

        [[1, 0, 4, 7, 8],
         [0, 6, 0, 0, 9],
         [7, 2, 4, 3, 1],
         [2, 9, 8, 8, 7]]],


       [[[1, 5, 7, 1, 9],
         [2, 5, 4, 0, 3],
         [3, 0, 5, 3, 9],
         [6, 1, 7, 0, 6]],

        [[5, 0, 9, 7, 9],
         [6, 1, 7, 5, 3],
         [4, 6, 7, 3, 4],
         [3, 8, 3, 2, 5]],

        [[0, 7, 7, 5, 0],
         [8, 2, 0, 0, 0],
         [1, 6, 8, 6, 2],
         [3, 3, 2, 1, 6]]]])

In [73]:
a4.shape

(2, 3, 4, 5)

In [78]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [79]:
a3*a4

ValueError: operands could not be broadcast together with shapes (2,2,3) (2,3,4,5) 

In [76]:
a3.shape

(2, 2, 3)

In [80]:
a3_resize=a3.reshape(2,2,3,1)

In [81]:
a3_resize*a4

ValueError: operands could not be broadcast together with shapes (2,2,3,1) (2,3,4,5) 

In [82]:
np.random.seed()
things = np.random.randint(20,size = (5,3))
things

array([[11,  9,  0],
       [17, 14,  9],
       [11,  5, 14],
       [11,  6, 12],
       [17,  0,  7]])

In [84]:
things_df = pd.DataFrame(things , index = ["mon" , "tue" , "wed" , "thu", "fri"],
                        columns = ["butter","milk","chiz"])
things_df

butter  milk  chiz
mon      11     9     0
tue      17    14     9
wed      11     5    14
thu      11     6    12
fri      17     0     7

In [86]:
price = np.array([10,12,8])
price

array([10, 12,  8])

In [100]:
things_df.shape

(5, 3)

In [101]:
price.reshape(1,3)

array([[10, 12,  8]])

In [104]:
price_df = pd.DataFrame(price.reshape(1,3) , index = ["price"],
                       columns =["butter","milk","chiz"])
price_df

butter  milk  chiz
price      10    12     8

In [110]:
total = price.dot(things.T)
total

array([218, 410, 282, 278, 226])

In [111]:
things_df

butter  milk  chiz
mon      11     9     0
tue      17    14     9
wed      11     5    14
thu      11     6    12
fri      17     0     7

In [115]:
things_df["Total"] = price_df.T
things_df

butter  milk  chiz  Total
mon      11     9     0    NaN
tue      17    14     9    NaN
wed      11     5    14    NaN
thu      11     6    12    NaN
fri      17     0     7    NaN

In [116]:
things_df["Total"]

butter  milk  chiz  Total
mon      11     9     0    NaN
tue      17    14     9    NaN
wed      11     5    14    NaN
thu      11     6    12    NaN
fri      17     0     7    NaN

In [12]:
<img src="image/fee receipt.png" \>

SyntaxError: invalid syntax (Temp/ipykernel_31588/2393125631.py, line 1)

In [15]:
from matplotlib.image import imread

ModuleNotFoundError: No module named 'matplotlib'